baseurl      = "https://will-l-dev.github.io/will-l-dev.github.io-next-blog/"
languageCode = "en-gb"
title        = "Somehow at Next"

defaultContentLanguage = "en"
hasCJKLanguage         = false

[pagination]
    pagerSize = 5

[taxonomies]
    tag      = "tags"
    category = "categories"
    series   = "series"
