[[main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 2
    [main.params]
        icon = "home"

[[main]]
    identifier = "posts"
    name       = "Daily Write-ups"
    url        = "/post/"
    weight     = 3
    [main.params]
        icon = "pencil"

[[main]]
    identifier = "agenda"
    name       = "My Agenda"
    url        = "/agenda/"
    weight     = 4
    [main.params]
        icon = "calendar-event"

[[main]]
    identifier = "food-events"
    name       = "Food & Events"
    url        = "/food-events/"
    weight     = 5
    [main.params]
        icon = "tools-kitchen-2"

[[main]]
    identifier = "travel"
    name       = "Travel Log"
    url        = "/travel/"
    weight     = 6
    [main.params]
        icon = "plane"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/will-l-dev"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/wlouzado"
    [social.params]
        icon = "brand-linkedin"
