# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = "Courtesy of <a href='https://www.bynd.com/' target='_blank'>Beyond</a> · If I have any views — they are my own"

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "☁️"
    subtitle = "Planned to come to Google Next as a Recruiter back in 2021.<br><br>Rocked up as a Senior Platform Engineer @ <a href='https://www.bynd.com/' target='_blank'>Beyond</a> instead.<br><br>Notes from Las Vegas, 2026.<br>If I have any views — they are my own."
    avatar   = "img/avatar.png"

[article]
    headingAnchor = true
    math          = false
    readingTime   = true

    [article.license]
        enabled = false

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "dark"

[comments]
    enabled = false
